In [ ]:
!pip install scikit-multilearn

     |████████████████████████████████| 89 kB 3.3 MB/s 


In [ ]:
!pip install scikit-learn==0.24.1

     |████████████████████████████████| 22.3 MB 116.1 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import hamming_loss, accuracy_score, precision_score
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB

In [ ]:
aspects_df = pd.read_csv('irony_train.csv')

In [ ]:
aspects_df1 = pd.read_csv('taskB.En.input.csv')

In [ ]:
X = aspects_df["tweet"]
y = np.asarray(aspects_df[aspects_df.columns[1:]])

# initializing TfidfVectorizer
vetorizar = TfidfVectorizer(max_features=3000, max_df=0.85)
# fitting the tf-idf on the given data
vetorizar.fit(X)

# splitting the data to training and testing data set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# transforming the data
X_train_tfidf = vetorizar.transform(X_train)
X_test_tfidf = vetorizar.transform(X_test)

In [ ]:
# initialize binary relevance multi-label classifier
# with a gaussian naive bayes base classifier
classifier = BinaryRelevance(GaussianNB())

In [ ]:
classifier.fit(X_train_tfidf,y_train)

BinaryRelevance(classifier=GaussianNB(), require_dense=[True, True])

In [ ]:
A = aspects_df1["text"]

In [ ]:
A_tfidf = vetorizar.transform(A)

In [ ]:
predicted = classifier.predict(X_test_tfidf)
predicted = predicted.toarray()

print(accuracy_score(y_test, predicted))
print(hamming_loss(y_test, predicted))
print(precision_score(y_test, predicted, average=None))

0.5919540229885057
0.14367816091954022
[0.83006536 0.         0.         0.         0.         0.1       ]


In [ ]:
predicted = classifier.predict(A_tfidf)
predicted = predicted.toarray()

In [ ]:
print(predicted)

[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 1 1 1 1]
 ...
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]


In [ ]:
",".join(str(predicted))

'[,[,1, ,0, ,0, ,0, ,0, ,0,],\n, ,[,1, ,0, ,0, ,0, ,0, ,0,],\n, ,[,0, ,1, ,1, ,1, ,1, ,1,],\n, ,.,.,.,\n, ,[,1, ,0, ,0, ,0, ,0, ,0,],\n, ,[,1, ,0, ,0, ,0, ,0, ,0,],\n, ,[,1, ,0, ,0, ,0, ,0, ,0,],]'

In [ ]:
np.savetxt("predictionsB.txt", predicted, fmt="%s",)